title: Potofolio
name: Miftakhuddin Falaki
email: miftakhuddinfalaki@gmail.com
description: >-
  Web Resume.
baseurl: "/profile" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
img_av: "/assets/img/profile-img4.png"
github_username: kikukeii
env_c: qwertyuiop
permalink: "/:title/"
# Build settings
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
aboutme: >-
  Dilahirkan di Kabupaten Tangerang tepatnya di Kampung Desa Bakung Kecamatan Kronjo pada hari Selasa tanggal 7 Maret 2000. Anak kedua dari tiga bersaudara. Peneliti menyelesaikan pendidikan di Sekolah Dasar di SD N Pasilian II Kecamatan Kronjo Kabupaten Tangerang pada tahun 2012 Pada tahun itu juga peneliti melanjutkan Pendidikan di SMP Negeri 1 Kronjo Kecamatan Kronjo dan tamat pada tahun 2015 kemudian melanjutkan Sekolah Menengah Kejuruan dan mengambil kejuruan Multimedia di SMK Mandiri 02 Balaraja Kecamatan Balaraja Kabupaten Tangerang pada tahun 2015 dan selesai pada tahun 2018. Pada tahun 2018 peneliti melanjutkan pendidikan di perguruan tinggi di Jakarta Selatan, tepatnya di Universitas Indraprasata PGRI (Unindra) Fakultas Teknik dan Ilmu Komputer pada Program Studi Teknik Informatika.<br><br>Dalam melaksanakan kuliah saya sangat tertarik dalam percodingan hingga mempelajari lebih dari satu bahasa pemrograman. Hingga kini saya setidaknya familiar dengan beberapa bahasa pemrograman. Keinginan terbesar saya saat ini adalah membuat sebuah sistem yang nantinya berguna untuk perkembangan teknologi.
shortaboutme: >-
  Sarjana Komputer dengan 3.55 GPA. Semangat dalam bekerja. Familiar dengan bahasa pemrograman PHP, SQL, dan Javascript serta Rest API. Bisa membuat aplikasi dengan Framework PHP atau Library Javascipt. Dapat membuat program baru dan mampu mengimplemetasikannya. Serta dapat bekerja sama dengan Tim.
